
package javaassignmentd.d;

import javax.swing.JOptionPane;

/**
 *
 * @author Cortland Boudreau
 */
public class GameframeMainFrame extends javax.swing.JFrame {

GameCharacter charHero = new GameCharacter("Sir Lenard",140);

Monster monster=new Monster("Small Goo", 50);
Weapon weaponSelect= new Weapon();
Armor armorSelect = new Armor();

// vars
int intMainTruearmor=0;
int intTrueMin=0;
int intTrueMax=0;
int intCharhp=140;
String stringName="Sir Lenard";
int intMonsterdmg=0;
int intMonsterhp=0;
String stringMname="Small goo";

GameframeArmory armoryForm = new GameframeArmory();
GameframeMonsters monsterForm = new GameframeMonsters();





    /** Creates new form GameframeMainFrame */
    public GameframeMainFrame() {
        
        initComponents();
        
        
        
     
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGivename = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Neverwinter", 0, 36));
        jLabel2.setText("Monster Arena");

        jButton1.setText("Armory");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("The armory lets you select weapons and armor.");

        jButton2.setText("Holding Pens");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("The Holding pens lets you select the type of monster");

        jLabel4.setText("you wish to fight.");

        btnGivename.setText("Update Character name");
        btnGivename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGivenameActionPerformed(evt);
            }
        });

        txtName.setText("Sir Lenard");

        btnStart.setText("Enter Arena");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnGivename, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(110, 110, 110)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGivename)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// set armory form visible 
        armoryForm.setVisible(true);
  
    
}//GEN-LAST:event_jButton1ActionPerformed

private void btnGivenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGivenameActionPerformed

    
    stringName=txtName.getText();
    
    
    
    if (validateName(stringName)){
		
	this.charHero.stringName=stringName;
	 
	 }
	
	else{
		
	   JOptionPane.showMessageDialog(null, "Please enter another name, ERROR::."); 
	}

    
}//GEN-LAST:event_btnGivenameActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  monsterForm.setVisible(true);
}//GEN-LAST:event_jButton2ActionPerformed

private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
    
    // abstraction methods
    charHero.sendInfo();
monster.sendInfo();

// get values from the forms and put them into a class
    this.monster.intDmg=monsterForm.intDamage;
    this.weaponSelect.min=armoryForm.intTrueMin;
    this.weaponSelect.max=armoryForm.intTrueMax;
    this.armorSelect.intDamagereduc=armoryForm.intTruearmor;
    this.monster.stringName=monsterForm.getMonster();
    this.monster.intHp=monsterForm.getHp();
   
   // call methods of object and put them into vars to put into the new frame
   int intArmor = armorSelect.getArmoritem();
    intCharhp=charHero.getHp();
    stringMname=monster.getName();
    stringName=charHero.getName();
    stringMname=this.monster.stringName;
    intTrueMax=weaponSelect.getMaxdamage();
    intTrueMin=weaponSelect.getMindamage();
    intMonsterhp=monster.getHp();
    
    
    // make the battle frame with the vars that we just got
    GameBattleframe battleForm = new GameBattleframe(intMonsterhp,intCharhp,intTrueMax,intTrueMin,intMonsterdmg,stringName,stringMname, intArmor );
   
    battleForm.setVisible(true);
}//GEN-LAST:event_btnStartActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameframeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameframeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameframeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameframeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GameframeMainFrame().setVisible(true);
            }
        });
    }
    
    
  public int getTrueArmor() {
           intMainTruearmor = armoryForm.getTrueArmor();
            // get  the value of armor from the object
            
  return intMainTruearmor;
}    
    
public int getTrueMax() {
           intTrueMax = armoryForm.getTrueMax();
            // get the value of max damage
            
  return intTrueMax;
}    
      
      
public int getTrueMin() {
           intTrueMin = armoryForm.getTrueMin();
            // get the value of min damage

  return intTrueMin;
}

   public static boolean validateName(String S_input){
    boolean valid = true;
   
    
    
    if (S_input.length() == 0)  // set valid to 'false' if empty string
        valid = false;
    
    else {
    	valid=true;
    }
          
    return valid;
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGivename;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
