
package javaassignmentd.d;


public class GameframeArmory extends javax.swing.JFrame {
      int intTrueMin=4;
      int intTrueMax=7;
      int intTruearmor=3;
 
        

    /** Creates new form GameframeArmory */
    public GameframeArmory() {
        initComponents();
           this.txtMinDmg.setText("4");
           this.txtMaxDmg.setText("7");
           this.dmgReduc.setText("3");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnMonster = new javax.swing.JButton();
        txtMinDmg = new javax.swing.JTextField();
        txtMaxDmg = new javax.swing.JTextField();
        dmgReduc = new javax.swing.JTextField();
        cboWeapon = new javax.swing.JComboBox();
        cboArmor = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Game");

        jLabel2.setFont(new java.awt.Font("Neverwinter", 0, 36)); // NOI18N
        jLabel2.setText("This is the Armory. ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel3.setText("Weapons");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Armor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Minimum Damage:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Maximum Damage:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Damage Reduction:");

        btnMonster.setText("Close Armory");
        btnMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonsterActionPerformed(evt);
            }
        });

        txtMinDmg.setName(""); // NOI18N
        txtMinDmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinDmgActionPerformed(evt);
            }
        });

        txtMaxDmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxDmgActionPerformed(evt);
            }
        });

        cboWeapon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "One handed Sword", "One handed Axe", "One handed Mace" }));
        cboWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboWeaponActionPerformed(evt);
            }
        });

        cboArmor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Leather Armor", "Chainmail Armor", "Full plate Armor" }));
        cboArmor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboArmorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(btnMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMaxDmg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMinDmg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dmgReduc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4)))
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel2)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(dmgReduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(cboArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))
                        .addGap(42, 42, 42)
                        .addComponent(btnMonster, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(cboWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMinDmg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaxDmg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addGap(74, 74, 74)))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtMinDmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinDmgActionPerformed

}//GEN-LAST:event_txtMinDmgActionPerformed

private void txtMaxDmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxDmgActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtMaxDmgActionPerformed

private void btnMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonsterActionPerformed
// close the form
    
    this.setVisible(false);

}//GEN-LAST:event_btnMonsterActionPerformed

private void cboWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboWeaponActionPerformed
 if(this.cboWeapon.getSelectedIndex()==0)
        {        
            
            // item1 stats
           this.txtMinDmg.setText("4");
           this.txtMaxDmg.setText("7");
           intTrueMin=4;
           intTrueMax=7;
        }
        if(this.cboWeapon.getSelectedIndex()==1)
        { 
            
            // item2 stats
           this.txtMinDmg.setText("5");
           this.txtMaxDmg.setText("8");
              intTrueMin=5;
           intTrueMax=8;
        
        }   
          if(this.cboWeapon.getSelectedIndex()==2)
        { 
        //item 3 stats
           this.txtMinDmg.setText("9");
           this.txtMaxDmg.setText("11");
            intTrueMin=9;
           intTrueMax=11;
        }   

}//GEN-LAST:event_cboWeaponActionPerformed

private void cboArmorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboArmorActionPerformed

     if(this.cboArmor.getSelectedIndex()==0){   
         
         this.dmgReduc.setText("2");
          intTruearmor=2;

          // item 4 stats
        }
        if(this.cboArmor.getSelectedIndex()==1){ 
            
            // item 5 stats
             this.dmgReduc.setText("4");
        intTruearmor=4;
        
        }   
          if(this.cboArmor.getSelectedIndex()==2){ 
              // item 6 stats
               this.dmgReduc.setText("8");
     intTruearmor=8;
        }
    
}//GEN-LAST:event_cboArmorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameframeArmory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameframeArmory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameframeArmory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameframeArmory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GameframeArmory().setVisible(true);
            }
        });
    }
    
    
    
    
    public int getTrueMax() {
  return intTrueMax;
  
  // return the max damage of the wep
}
    
        public int getTrueMin() {
            
            // return the min damage of the wep
  return intTrueMin;
}
     public int getTrueArmor() {
         
         // return the damage reduction of the armor
  return intTruearmor;
}   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMonster;
    private javax.swing.JComboBox cboArmor;
    private javax.swing.JComboBox cboWeapon;
    private javax.swing.JTextField dmgReduc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtMaxDmg;
    private javax.swing.JTextField txtMinDmg;
    // End of variables declaration//GEN-END:variables
}
