/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GameBattleframe.java
 *
 * Created on Mar 22, 2012, 9:05:30 AM
 */
package javaassignmentd.d;
import javax.swing.JOptionPane;
import java.util.Random;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;




public class GameBattleframe extends javax.swing.JFrame {

    private class TimerEventAction implements ActionListener
    {
        // What happens when the event occurs
        public void actionPerformed( ActionEvent actionEvent )
        {
            intTime=intTime+1;
            
            //displays the updated time
         txtTimers.setText(Integer.toString(intTime));
           
        } 
    }// end class TimerEventAction
    

    int intTime=0;
    private int intMonh;
    private int intCharh;
    private final int intCharmin;
    private final int intCharmax;
    private final int intMondmg;
    private final String sCharn;
    private final String sMonn;
    private final int intDef;
    
    // 1000 miliseconds
private final int Time = 1000;


    // timer Object
    Timer Timer = new Timer( Time, new TimerEventAction() );

    // make attack object
    Attack swing= new Attack();
    
    // make random object
  Random random = new Random();
 
  

    /** Creates new form GameBattleframe */
    public GameBattleframe(int intMonhp, int intCharhp, int intCharmaxdmg,int intCharmindmg,int intMonsterdmg, String stringCharname,String stringMonname, int intArmor) {
        initComponents();
        
        // give txt the correct strings
        Timer.start(); // Start timer
        this.txtMon.setText(stringMonname);
          this.txtCharname.setText(stringCharname);
          this.txtMonsterhp.setText(Integer.toString(intMonhp)); 
          this.txtHerohp.setText(Integer.toString(intCharhp)); 
          
         // take input vars and give them local vars
        sMonn=stringMonname;          
        sCharn=stringCharname;         
        intCharmin=intCharmindmg;
        intCharmax=intCharmaxdmg;
        intCharh=intCharhp;
        intMonh=intMonhp;
        intMondmg=intMonsterdmg;
        intDef= intArmor; 
  
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAttack = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMonsterhp = new javax.swing.JTextField();
        txtHerohp = new javax.swing.JTextField();
        txtCharname = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        txtTimers = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMon = new javax.swing.JLabel();
        txtcombat1 = new javax.swing.JTextField();
        txtcombat2 = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAttack.setText("Attack!");
        btnAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("HP:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("HP:");

        txtMonsterhp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtHerohp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtCharname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCharname.setText("<Default>");

        lblTimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTimer.setText("Combat has lasted for");

        txtTimers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimersActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("seconds.");

        txtMon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMon.setText("Monster");

        txtcombat1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcombat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcombat1ActionPerformed(evt);
            }
        });

        txtcombat2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcombat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcombat2ActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonsterhp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtcombat1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(txtcombat2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimers, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtCharname, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMon)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2)
                    .addContainerGap(505, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(txtHerohp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(378, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonsterhp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCharname)
                    .addComponent(txtMon))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcombat1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcombat2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(351, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(txtHerohp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(353, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttackActionPerformed

int intDamagecalc=0;
int intHerohp=intCharh;
int intGoohp=intMonh;

Attack swing= new Attack();

 // random attack/time calc that isn't finished


// damage and hp calcs
intDamagecalc=intCharmin+ random.nextInt(intCharmax);
intDamagecalc=swing.getAttack(intDamagecalc);
intDamagecalc=intDamagecalc-intDef;
intGoohp=intGoohp-intDamagecalc;
        



this.txtMonsterhp.setText(Integer.toString(intGoohp)); 
this.txtcombat1.setText(sMonn+" hits the monster for "+intDamagecalc );

if(intGoohp<=0){
    // monster death
   JOptionPane.showMessageDialog(null, "The Goo Monster has died.");
this.dispose();
   
}
 // damage and hp calcs
intDamagecalc=swing.getAttack(intMondmg);
intHerohp=intHerohp-intDamagecalc;    
this.txtHerohp.setText(Integer.toString(intHerohp)); 
this.txtcombat2.setText(sCharn+" hits the monster for "+intDamagecalc );

if(intHerohp<=0){
    // hero death
       JOptionPane.showMessageDialog(null, "The Hero has died.");
this.dispose();
 
}    

intCharh=intHerohp;
intMonh= intGoohp;

}//GEN-LAST:event_btnAttackActionPerformed

private void txtcombat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcombat1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtcombat1ActionPerformed

private void txtcombat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcombat2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtcombat2ActionPerformed

private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
// dispose form, not hide, because we might want new values for the form
    this.dispose();
}//GEN-LAST:event_btnCloseActionPerformed

private void txtTimersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimersActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtTimersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBattleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBattleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBattleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBattleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GameBattleframe(0,0,0,0,0,"","",0).setVisible(true);
            }
        });
    }
    
      
                              
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAttack;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel txtCharname;
    private javax.swing.JTextField txtHerohp;
    private javax.swing.JLabel txtMon;
    private javax.swing.JTextField txtMonsterhp;
    private javax.swing.JTextField txtTimers;
    private javax.swing.JTextField txtcombat1;
    private javax.swing.JTextField txtcombat2;
    // End of variables declaration//GEN-END:variables
}
